export const AppRoutes = {
  HOME: '/',
  MY_COURSES:'/my-courses',
  MARKETPLACE:'/marketplace',
  ADD_COURSE:'/add-course',
  EDIT_COURSE:'/edit-course',
  LOGIN:'/login',
  SIGNUP:'/sign-up',
  FORGOT_PASSWORD:'/forgot-password',
  DASHBOARD:'/dashboard',
  ADD_CART:'/add-cart',
  COURSE_DETAILS:'/course-details',
  CONTACTUS:'/contact-us',
  ABOUTUS:'/about-us',
  COURSE_BUILDER:'/course-builder',
};
