const coursesItem = [
    {
        id: "1",
        courseTag: "Art & Design",
        courseTagColor: "skyblue",
        courseImage: "https://myheart.net/wp-content/uploads/2013/12/dreamstimelarge_211129061.jpg",
        courseName: "Overcomming Negative Family Patterns",
        courseOwnerProfile: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        courseOwner: "Jassica Miller",
        courseButton: "Start Course",
        courseType: "Create Course",
        courseDate: "May 12, 2022",
    },
    {
        id: "2",
        courseTag: "Marketing",
        courseTagColor: "purple",
        courseImage: "https://imgk.timesnownews.com/story/Health_benefits_of_Aerial_Yoga.jpg",
        courseName: "Yoga Super Shered for Men",
        courseOwnerProfile: "https://www.jeancoutu.com/globalassets/revamp/photo/conseils-photo/20160302-01-reseaux-sociaux-profil/photo-profil_301783868.jpg",
        courseOwner: "Jassica Miller 2",
        courseButton: "Start Course",
        courseType: "Purchase Course",
        courseDate: "June 05, 2022",
    },
    {
        id: "3",
        courseTag: "UX Design",
        courseTagColor: "pink",
        courseImage: "https://circuitliving.com/wp-content/uploads/2021/09/stretching-before-a-workout-519x519.jpg",
        courseName: "Fit and Fierce Over 40",
        courseOwnerProfile: "https://www.whatsappprofiledpimages.com/wp-content/uploads/2021/08/Profile-Photo-Wallpaper.jpg",
        courseOwner: "Jassica Miller",
        courseButton: "Start Course",
        courseType: "Create Course",
        courseDate: "August 22, 2021",
      },
      {
          id: "4",
          courseTag: "Art & Design",
        courseTagColor: "skyblue",
          courseImage: "https://images.squarespace-cdn.com/content/v1/5c9642c0ab1a6250fa3dc676/1555701147382-444B47HZZWG2FKWQ69FI/Lines-Website-Homepage-Banner.jpg?format=2500w",
          courseName: "Shakti Warrior Dance for Healing",
          courseOwnerProfile: "https://www.jeancoutu.com/globalassets/revamp/photo/conseils-photo/20160302-01-reseaux-sociaux-profil/photo-profil_301783868.jpg",
          courseOwner: "Jassica Miller 2",
          courseButton: "Start Course",
            courseType: "Purchase Course",
            courseDate: "August 22, 2021",
      },
      {
        id: "5",
        courseTag: "Marketing",
        courseTagColor: "purple",
        courseImage: "https://myheart.net/wp-content/uploads/2013/12/dreamstimelarge_211129061.jpg",
        courseName: "Overcomming Negative Family Patterns",
        courseOwnerProfile: "https://www.whatsappprofiledpimages.com/wp-content/uploads/2021/08/Profile-Photo-Wallpaper.jpg",
        courseOwner: "Jassica Miller",
        courseButton: "Start Course",
        courseType: "Create Course",
        courseDate: "August 22, 2021",
      
    },
    {
        id: "6",
        courseTag: "UX Design",
        courseTagColor: "pink",
        courseImage: "https://imgk.timesnownews.com/story/Health_benefits_of_Aerial_Yoga.jpg",
        courseName: "Yoga Super Shered for Men",
        courseOwnerProfile: "https://www.jeancoutu.com/globalassets/revamp/photo/conseils-photo/20160302-01-reseaux-sociaux-profil/photo-profil_301783868.jpg",
        courseOwner: "Jassica Miller 2",
        courseButton: "Start Course",
        courseType: "Create Course",
        courseDate: "August 22, 2021",
    },
    {
        id: "7",
        courseTag: "Art & Design",
        courseTagColor: "skyblue",
        courseImage: "https://circuitliving.com/wp-content/uploads/2021/09/stretching-before-a-workout-519x519.jpg",
        courseName: "Fit and Fierce Over 40",
        courseOwnerProfile: "https://www.whatsappprofiledpimages.com/wp-content/uploads/2021/08/Profile-Photo-Wallpaper.jpg",
        courseOwner: "Jassica Miller",
        courseButton: "Start Course",
        courseType: "Purchase Course",
        courseDate: "August 22, 2021",
      },
      {
          id: "8",
          courseTag: "Marketing",
        courseTagColor: "purple",
          courseImage: "https://images.squarespace-cdn.com/content/v1/5c9642c0ab1a6250fa3dc676/1555701147382-444B47HZZWG2FKWQ69FI/Lines-Website-Homepage-Banner.jpg?format=2500w",
          courseName: "Shakti Warrior Dance for Healing",
          courseOwnerProfile: "https://www.jeancoutu.com/globalassets/revamp/photo/conseils-photo/20160302-01-reseaux-sociaux-profil/photo-profil_301783868.jpg",
          courseOwner: "Jassica Miller 2",
          courseButton: "Start Course",
        courseType: "Create Course",
        courseDate: "August 22, 2021",
      },
      {
        id: "9",
        courseTag: "UX Design",
        courseTagColor: "pink",
        courseImage: "https://images.squarespace-cdn.com/content/v1/5c9642c0ab1a6250fa3dc676/1555701147382-444B47HZZWG2FKWQ69FI/Lines-Website-Homepage-Banner.jpg?format=2500w",
        courseName: "Shakti Warrior Dance for Healing",
        courseOwnerProfile: "https://www.jeancoutu.com/globalassets/revamp/photo/conseils-photo/20160302-01-reseaux-sociaux-profil/photo-profil_301783868.jpg",
        courseOwner: "Jassica Miller 2",
        courseButton: "Start Course",
      courseType: "Create Course",
      courseDate: "August 22, 2021",
    },
  ];

  export default coursesItem